import { Muscle } from "@/_api/interface";
import { musclesImages } from "../assets";

const karmtuomieji_raumenys: Record<string, Omit<Muscle, "id">> = {
  kramtomasis_raumuo: {
    latin: "Masseter",
    group: "Kramtomieji raumenys",
    name: "Kramtomasis raumuo",
    pictures: musclesImages.kramtomasis_raumuo,
    start: "Skruostinis lankas",
    finish: "Apatinio žandikaulio kampas",
    function: "Kelia žandikaulį į viršų",
  },
  smilkininis_raumuo: {
    latin: "Temporalis",
    group: "Kramtomieji raumenys",
    name: "Smilkininis raumuo",
    pictures: musclesImages.smilkininis_raumuo,
    start: "Smilkinio duobės paviršius",
    finish: "Vainikinė apatinio žandikaulio atauga",
    function: "Kelia apatinį žandikaulį ir traukia jį atgal",
  },
  soninis_sparninis_raumuo: {
    latin: "Lateral pterygoid",
    group: "Kramtomieji raumenys",
    name: "Šoninis sparninis raumuo",
    pictures: musclesImages.soninis_sparninis_raumuo,
    start: "Pleištakaulio posmilkininio didžiojo sparno paviršius",
    finish: "Apatinio žandikaulio krumplinė atauga ir sąnario diskas",
    function:
      "Abiejose pusėse susitraukdami stumia žandikaulį į priekį, vienos pusės – suka žandikaulį į priešingą pusę",
  },
  vidinis_sparninis_raumuo: {
    latin: "Medial pterygoid",
    group: "Kramtomieji raumenys",
    name: "Vidinis sparninis raumuo",
    pictures: musclesImages.vidinis_sparninis_raumuo,
    start: "Duobė tarp abiejų pleištakaulio sparninės ataugos lokštelių",
    finish: "Apatinio žandikaulio kampo vidinis paviršius",
    function: "Kelia žandikaulį į viršų",
  },
  antgalvinis_raumuo_kaktinis_pilvelis: {
    latin: "Ocipitofrontalis",
    group: "Kaukolės skliauto raumenys",
    name: "Antgalvinis raumuo (kaktinis pilvelis)",
    pictures: musclesImages.antgalvinis_raumuo_kaktinis_pilvelis,
    start: "Sausplėvinis šalmas",
    finish: "Antakių oda",
    function:
      "Kelia antakius, sutraukia kaktos odą ir traukia sausplėvinį šalmą su oda į priekį",
  },
  antgalvinis_raumuo_pakausinis_pilvelis: {
    latin: "Ocipitofrontalis",
    group: "Kaukolės skliauto raumenys",
    name: "Antgalvinis raumuo (Pakauš pilvelis)",
    pictures: musclesImages.antgalvinis_raumuo_pakausinis_pilvelis,
    start: "Pakauškaulio sprandinė linija",
    finish: "Sausplėvinis šalmas",
    function: "Traukia susplėvinį šalmą su oda atgal",
  },
  ausies_aplinkos_raumenys: {
    latin: "Auriicularis",
    group: "Ausies aplinkos raumenys",
    name: "Ausies aplinkos raumenys",
    pictures: musclesImages.ausies_aplinkos_raumenys,
    start: "Kaukolės kaulai",
    finish: "Ausies kremzlė",
    function: "Pakeičia ausies padėtį",
  },
  ziedinis_akies_raumuo: {
    latin: "Auriicularis",
    group: "Akies aplinkos raumenys",
    name: "Žiedinis akies akmuo",
    pictures: musclesImages.ziedinis_akies_raumuo,
    start: "Kaktikaulio nosinė dalis",
    finish: "Šoninis akiduobės kraštas",
    function:
      "Sudaro raukšles apie akį, nuleidžia antakius, pakelia skruosto odą",
  },
  antakiu_sutraukiamasis_raumuo: {
    latin: "Corrugator supercilii",
    group: "Akies aplinkos raumenys",
    name: "Antakių sutraukiamasis raumuo",
    pictures: musclesImages.antakiu_sutraukiamasis_raumuo,
    start: "Kaktikaulio nosinė dalis",
    finish: "Antakių oda",
    function: "Sutraukia antakius",
  },
  suglaudziamasis_snerves_raumuo: {
    latin: "Compressor naris",
    group: "Nosies raumenys",
    name: "Suglaudžiamasis šnerves raumuo",
    pictures: musclesImages.suglaudziamasis_snerves_raumuo,
    start: "Nosies kaulai",
    finish: "Nosies kremzlė",
    function: "Suspaudžia nosies sparnus",
  },
  pleciamasis_snerves_raumuo: {
    latin: "Dilator naris",
    group: "Nosies raumenys",
    name: "Plėčiamasis šnerves raumuo",
    pictures: musclesImages.pleciamasis_snerves_raumuo,
    start: "Nosies kaulai",
    finish: "Nosies kremzlė",
    function: "Plėčia nosies sparnus",
  },
  nosies_pertvaros_raumuo: {
    latin: "Depressor septi",
    group: "Nosies raumenys",
    name: "Pertvaros raumuo",
    pictures: musclesImages.nosies_pertvaros_raumuo,
    start: "Nosies kaulai",
    finish: "Nosies kremzlė",
    function: "Nuleidžia nosies pertvarą",
  },
  ziedinis_burnos_raumuo: {
    latin: "Orbicularis oris",
    group: "Burnos raumenys",
    name: "Žiedinis burnos raumuo",
    pictures: musclesImages.ziedinis_burnos_raumuo,
    start: "Burnos kampai",
    finish: "Burnos kampai",
    function: "Uždaro burną, išstumia orą",
  },
  nuleidziamasis_aptines_lupos_raumuo: {
    latin: "Depressor anguli oris",
    group: "Burnos raumenys",
    name: "Nuleidžiamasis apatinės lūpos raumuo",
    pictures: musclesImages.nuleidziamasis_aptines_lupos_raumuo,
    start: "Apatinė žandikaulio dalis",
    finish: "Apatinė lūpa",
    function: "Nuleidžia apatinę lūpą",
  },
  keliamasis_virsutines_lupos_raumuo: {
    latin: "Levator labii superioris",
    group: "Burnos raumenys",
    name: "Keliajamasis viršutinės lūpos raumuo",
    pictures: musclesImages.keliamasis_virsutines_lupos_raumuo,
    start: "Apatinė nosies dalis",
    finish: "Viršutinė lūpa",
    function: "Kelia viršutinę lūpą",
  },
  didysis_ir_mazasis_skruosto_raumenys: {
    latin: "Zygomaticus major et minor",
    group: "Skruosto raumenys",
    name: "Didysis ir mažasis skruosto raumenys",
    pictures: musclesImages.didysis_ir_mazasis_skruosto_raumenys,
    start: "Skruostinis lankas",
    finish: "Burnos kampai",
    function: "Pakelia burnos kampus",
  },
  juoko_raumuo: {
    latin: "Risorius",
    group: "Burnos raumenys",
    name: "Juoko raumuo",
    pictures: musclesImages.juoko_raumuo,
    start: "Apatinė žandikaulio dalis",
    finish: "Burnos kampai",
    function: "Išstumia burnos kampus į šonus",
  },
  nuleidzimasis_lupu_kampo_raumuo: {
    latin: "Depressor anguli oris",
    group: "Burnos raumenys",
    name: "Nuleidžiamasis lūpų kampo raumuo",
    pictures: musclesImages.nuleidzimasis_lupu_kampo_raumuo,
    start: "Apatinė žandikaulio dalis",
    finish: "Burnos kampai",
    function: "Nuleidžia burnos kampus",
  },
  keliamasis_lupu_kampo_raumuo: {
    latin: "Levator anguli oris",
    group: "Burnos raumenys",
    name: "Keliajamasis lūpų kampo raumuo",
    pictures: musclesImages.keliamasis_lupu_kampo_raumuo,
    start: "Apatinė žandikaulio dalis",
    finish: "Burnos kampai",
    function: "Kelia burnos kampus",
  },
  zandinis_raumuo: {
    latin: "Buccinator",
    group: "Kalbos raumenys",
    name: "Žandinis raumuo",
    pictures: musclesImages.zandinis_raumuo,
    start: "Apatinė žandikaulio dalis",
    finish: "Liežuvio šaknis",
    function: "Traukia liežuvį į priekį",
  },
  poodinis_kaklo_raumuo: {
    latin: "Platysma",
    group: "Paviršiniai kaklo raumenys",
    name: "Poodinis kaklo raumuo",
    pictures: musclesImages.poodinis_kaklo_raumuo,
    start: "Kaklo kaulai",
    finish: "Kaklo oda",
    function: "Traukia kaklo odą į priekį",
  },
  sukamasis_galvos_raumuo: {
    latin: "Sternocleidomastoideus",
    group: "Paviršiniai kaklo raumenys",
    name: "Sukamasis galvos raumuo",
    pictures: musclesImages.sukamasis_galvos_raumuo,
    start: "Krūtinės kaulai",
    finish: "Kaklo kaulai",
    function: "Traukia galvą į šoną, lenkia ir suka",
  },
  priekinis_laiptinis_raumuo: {
    latin: "Scalenus anterior",
    group: "Gilieji kaklo raumenys",
    name: "Priekinis laiptinis raumuo",
    pictures: musclesImages.priekinis_laiptinis_raumuo,
    start: "Vidurinių kaklo slankstelių skersinės ataugos (C3-C6)",
    finish: "1 šonkaulio viršutinis paviršius",
    function:
      "Pakelia 1 šonkaulį, esant fiksuotam šonkauliui lenkia galvą į savo pusę, abiejų pusių lenkia galvą į priekį",
  },
  vidurinis_laiptinis_raumuo: {
    latin: "Scalenus medius",
    group: "Gilieji kaklo raumenys",
    name: "Vidurinis laiptinis raumuo",
    pictures: musclesImages.vidurinis_laiptinis_raumuo,
    start: "Visos kaklo slankstelių skersinės ataugos",
    finish: "1 šonkaulio viršutinis paviršius",
    function:
      "Pakelia I šonkaulį, esant fiksuotam šonkauliui lenkia galvą į savo pusę, abiejų pusių lenkia galvą į priekį",
  },
  uzpakalinis_laiptinis_raumuo: {
    latin: "Scalenus posterior",
    group: "Gilieji kaklo raumenys",
    name: "Užpakalinis laiptinis raumuo",
    pictures: musclesImages.uzpakalinis_laiptinis_raumuo,
    start: "Apatinių kaklo slankstelių skersinės ataugos (C5-C7)",
    finish: "2 šonkaulio išorinis paviršius",
    function:
      "Pakelia 2 šonkaulį, esant fiksuotam šonkauliui lenkia galvą į savo pusę, abiejų pusių lenkia galvą į priekį",
  },
  ilgasis_kaklo_raumuo: {
    latin: "Longus colli",
    group: "Gilieji kaklo raumenys",
    name: "Ilgasis kaklo raumuo",
    pictures: musclesImages.ilgasis_kaklo_raumuo,
    start:
      "Dviem galvomis nuo apatinio kaklo slankstelio ir viršutinių krūtinės slankstelių kūnų ir apatinių kaklo slankstelių skersinių ataugų",
    finish: "Viršutinių kaklo slankstelių kūnai ir atlanto priekinis lankas",
    function: "Lenkia kaklą į priekį ir į šoną",
  },
  ilgasis_galvos_raumuo: {
    latin: "Longus capitis",
    group: "Gilieji kaklo raumenys",
    name: "Ilgasis galvos raumuo",
    pictures: musclesImages.ilgasis_galvos_raumuo,
    start: "Vidurinių kaklo slankstelių skersinės ataugos",
    finish: "Pakauškaulio pamatas",
    function:
      "Susitraukdamas vienoje pusėje suka galvą į priešingą pusę, susitraukdamas abejose – lenkia į priekį",
  },
  priekinis_tiesusis_kaklo_raumuo: {
    latin: "Rectus capitis anterior",
    group: "Gilieji kaklo raumenys",
    name: "Priekinis tiesusis kaklo raumuo",
    pictures: musclesImages.priekinis_tiesusis_kaklo_raumuo,
    start: "Atlanto skersinė atauga",
    finish: "Pakauškaulio pamatas",
    function: "Lenkia galvą į priekį",
  },
  soninis_tiesusis_kaklo_raumuo: {
    latin: "Rectus capitis lateralis",
    group: "Gilieji kaklo raumenys",
    name: "Šoninis tiesusis kaklo raumuo",
    pictures: musclesImages.soninis_tiesusis_kaklo_raumuo,
    start: "Atlanto skersinė atauga",
    finish: "Pakauškaulio pamatass",
    function: "Lenkia galvą į šoną",
  },
};

const poliezuviniai_raumenys: Record<string, Omit<Muscle, "id">> = {
  dvipilvis_raumuo: {
    latin: "Digastricus",
    group: "Poliežuviniai raumenys",
    name: "Dvipilvis raumuo",
    pictures: musclesImages.dvipilvis_raumuo,
  },
  ylinis_poliezuvio_raumuo: {
    latin: "Stylohyoideus",
    group: "Poliežuviniai raumenys",
    name: "Ylinis poliežuvio raumuo",
    pictures: musclesImages.ylinis_poliezuvio_raumuo,
  },
  zandikaulinis_poliezuvio_raumuo: {
    latin: "Mylohyoideus",
    group: "Poliežuviniai raumenys",
    name: "Žandikaulinis poliežuvio raumuo",
    pictures: musclesImages.zandikaulinis_poliezuvio_raumuo,
  },
  smakrinis_poliezuvio_raumuo: {
    latin: "Geniohyoideus",
    group: "Poliežuviniai raumenys",
    name: "Smakrinis poliežuvio raumuo",
    pictures: musclesImages.smakrinis_poliezuvio_raumuo,
  },
  smakrinis_liezuvio_raumuo: {
    latin: "Hyoglossus",
    group: "Poliežuviniai raumenys",
    name: "Smakrinis liežuvio raumuo",
    pictures: musclesImages.smakrinis_liezuvio_raumuo,
  },
  ylinis_liezuvio_raumuo: {
    latin: "Styloglossus",
    group: "Poliežuviniai raumenys",
    name: "Ylinis liežuvio raumuo",
    pictures: musclesImages.ylinis_liezuvio_raumuo,
  },
  ylinis_rykles_raumuo: {
    latin: "Stylopharyngeus",
    group: "Poliežuviniai raumenys",
    name: "Ylinis ryklės raumuo",
    pictures: musclesImages.ylinis_rykles_raumuo,
  },
  metinis_poliezuvio_raumuo: {
    latin: "Omohyoideus",
    group: "Poliežuviniai raumenys",
    name: "Metinis poliežuvio raumuo",
    pictures: musclesImages.metinis_poliezuvio_raumuo,
  },
  krutininis_poliezuvio_raumuo: {
    latin: "Sternohyoideus",
    group: "Poliežuviniai raumenys",
    name: "Krūtininis poliežuvio raumuo",
    pictures: musclesImages.krutininis_poliezuvio_raumuo,
  },
  krutininis_skydo_raumuo: {
    latin: "Sternothyroideus",
    group: "Poliežuviniai raumenys",
    name: "Krūtininis skydo raumuo",
    pictures: musclesImages.krutininis_skydo_raumuo,
  },
};

export const headMucles = {
  ...karmtuomieji_raumenys,
  ...poliezuviniai_raumenys,
};
